name: 'Auto bump version'
description: 'Bump target branch version on PR merge'
inputs:
  major-label:
    description: 'Major version bump label'
    default: 'major'
  minor-label:
    description: 'Minor version bump label'
    default: 'minor'
  patch-label:
    description: 'Patch version bump label'
    default: 'patch'
runs:
  using: 'node12'
  main: 'index.js'
